# Generated by Django 6.0.3 on 2026-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
