# Generated by Django 6.0.3 on 2026-03-22 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_birthday_familynews_notification_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='familynews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='familynews',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
